[package]
name = "cve-2023-28244"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
chrono = "0.4.23"
clap = { version = "4.0.24", features = ["derive"] }
derive_more = "0.99.17"
futures = "0.3.25"
hex-literal = "0.3.4"
indicatif = { version = "0.17.2", features = ["tokio"] }
itertools = "0.10.5"
md4 = "0.10.2"
nom = "7.1.1"
pretty-hex = "0.3.0"
rand = "0.8.5"
rasn = "0.6.1"
rasn-kerberos = "0.6.0"
rc4 = "0.1.0"
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
utf16string = "0.2.0"
